#  servlet:
#    context-path:
#    compression:
#      enabled: true
#      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  # 设置静态文件路径，js,css等
  mvc:
    pathmatch:
      use-suffix-pattern: false
      use-registered-suffix-pattern: false
    contentnegotiation:
      favor-path-extension: false
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/**,classpath:/public/**
  #设置模版
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
